app:
  name: note_app_server
  host: localhost
  port: :8081
mysql:
  #  url
  dsn: "root:123@tcp(localhost:8077)/note_app_db?charset=utf8mb4&parseTime=True&loc=Local"
  # 最大并发连接数
  maxIdleConns: 10
  # 最大同时打开的连接数
  maxOpenConns: 100
  # 最大生命周期
  connMaxLifetime: 1h
redis:
  # 缓存笔记的点赞数/收藏数/统计刷入数据库的数据
  noteNormalRdb: 3
  # redis服务器地址（默认为localhost）
  host: localhost
  # redis端口（默认为6379）
  port: :8076
  # redis访问密码（默认为空）
  password:
  # redis连接超时时间（单位毫秒）
  timeout: 1500
  # redis连接池配置
  pool:
    # 最大可用连接数（默认为8，负数表示无限）
    maxActive: 30
    # 最大空闲连接数（默认为8，负数表示无限）
    maxIdle: 15
    # 最小空闲连接数（默认为0，该值只有为正数才有用）
    minIdle: 2
    # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
    maxWait: 1500
es:
  host: localhost
  port: 9200
mongo:
  host: localhost
  port: 8088
  username: root
  password: hanser
kafka:
  network: "tcp"
  host: localhost
  port: 9092
  # 点赞&取消点赞
  noteLikes:
    topic: "note_likes"
    partitions: 10
  # 收藏&取消收藏
  noteCollects:
    topic: "note_collects"
    partitions: 10
  # 评论笔记
  noteComments:
    topic: "note_comments"
    partitions: 10
  # 同步笔记
  syncNotes:
    topic: "sync_notes"
    partition: 10
  # 删除笔记
  delNotes:
    topic: "del_notes"
    partition: 10
  # 同步聊天记录
  syncMessages:
    topic: "sync_messages"
    partition: 10
oss:
  avatarBucket: "note-app-oss-avatar"
  notePicsBucket: "note-app-oss-note-pics"
  styleBucket: "note-app-oss-style"
  endPoint: "oss-cn-shanghai.aliyuncs.com"
  region: "cn-shanghai"